---
 - name: Launching aws ec2 instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
   - name: Launching ec2 instance with ec2 module 
     ec2:
      instance_type: t2.micro
      image: ami-092b43193629811af
      key_name: ohio-win
      region: us-east-2